### ISSUE TITLE
Make npm CI action run on direct push too

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1280]
https://github.com/jpatokal/openflights/blob/master/.github/workflows/npm.yaml

**Comment by reedy** [comment]
It seems a case of KISS... It does seem to do a merge on PR (so the commit hash looks wrong), but that's probably ok...

https://github.com/jpatokal/openflights/pull/1335 hash [59dd6d6](https://github.com/jpatokal/openflights/pull/1335/commits/59dd6d6c7320f64170661439b68130dc153fb0a8)

```
Checking out the ref
/usr/bin/git log -1 --format='%H'
'bc2d91758ee8e6f7c33962000d8986c8a155aea0'
```

[bc2d917](https://github.com/jpatokal/openflights/commit/bc2d91758ee8e6f7c33962000d8986c8a155aea0)

If we need/want to revisit it later..

```
name: NPM Actions

on:
  pull_request:
  push:

jobs:
  prettier-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: True
          prettier_version: 2.8.8

  prettier-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: True
          prettier_version: 2.8.8
```

Or a slightly condensed example (less duplication)
```
name: NPM Actions

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout Push
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: True
          prettier_version: 2.8.8
```
